import { Schema,model } from "./dbUtils.js";
import validator from "validator";

const productSchema = new Schema({
    name:{
        type:String,
        required:true
    },
    slug:String,
    brand:{
        type:Schema.Types.ObjectId,
        ref:'Brand',
        required:true
    },
    
    sizes:[
        {
            price:{
                type:Number,
                required:true,
                default:200
            },
            size:{
                type:String,
                required:true,
                default:"xl"
            },
        }
    ],
    colours:[
        {
            type:String,
        }
    ],
    tags:[
        {
            type:String,
        }
    ],
    description:{
        type:String,
        required:true
    },
    stock:{
        type:Number,
        required:true,
        default:1
    },
    rating:{
        type:Number,
        default:0
    },
    numOfReviews:{
        type:Number,
        default:0
    },
    reviews:[
        { 
            user:{
            type:Schema.Types.ObjectId,
            ref:'User',
            required:true
            },
            name:{
                type:String,
                required:true
            },
            rating:{
                type:Number,
                required:true,
            },
            comment:{
                type:String,
                required:true,
            },
        }
    ],
    images:[
        {
            public_id:{
                type:String,
                required:true
            },
            url:{
                type:String,
                required:true
            },
        }
    ],

    product_details:{
        package_dimension:{
            type:String,
            required:true
        },
        date_first_available:{
            type:Date,
            required:true
        },
        country_of_origin:{
            type:String,
            required:true
        },
        manufacturer:{
            type:String,
            required:true
        },
        
    },
    category:{
        type:Schema.Types.ObjectId,
        ref:'Cateegory'
    },
    sold:{
        type:Number,
        default:0
    },
    stock:{
        type:Number,
        default:0
    }
},{timestamps:true})

export const productModel = new model('Product',productSchema)